name: Grape Build
on:
  push:
    branches:
      - main

jobs:
  build-and-benchmark:
    name: Build and benchmark
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin git@github.com:jinjor/Grape.git
      - name: Cache Benchmark library
        uses: actions/cache@v2
        with:
          path: release-build/libs/benchmark
          key: ${{ runner.os }}-googlebenchmark
      - name: Build and run benchmark
        run: ./release-build.sh
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Grape Benchmark
          tool: "googlecpp"
          output-file-path: benchmark_result.json
          github-token: ${{ secrets.ALT_GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: "150%"
          comment-on-alert: true
          fail-on-alert: true
