name: Grape Build
on:
  push:
    branches:
      - main

jobs:
  build-and-benchmark:
    name: Build and benchmark
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache Benchmark library
        uses: actions/cache@v2
        with:
          path: |
            release-build/libs/benchmark
            release-build/src/CMakeFiles/GrapePlugin_VST3.dir/__/libs/JUCE
          key: ${{ runner.os }}-googlebenchmark-JUCE
      - name: Build and run benchmark
        run: ./release-build.sh
      - name: Store benchmark result
        uses: leoholz/github-action-benchmark@v1
        with:
          name: Grape Benchmark
          tool: "googlecpp"
          output-file-path: benchmark_result.json
          github-token: ${{ secrets.ALT_GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: "150%"
          comment-on-alert: true
          fail-on-alert: true
